### RUN ON:
# Push to main branch (after PR merge).

### JOBS:
# deploy:
# 1. Generate build files.
# 2. Provide AWS credentials
# 3. Push build files to S3
# 4. Invalidate CloudFront distribution cache

name: 'Deploy Application'

on:
  push:
    branches:
      - main

    paths-ignore:
      - public
      - .github/**
      - .gitignore
      - .prettierignore
      - .prettierrc.json
      - .eslintrc.cjs
      - README.md

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install deps
        run: npm ci

      - name: Create dist
        run: npm run build-static
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload dist files
        run: |
          aws s3 cp ./dist/ s3://${{ secrets.S3_BUCKET }}/ --recursive
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"