### RUN ON:
# Push to main branch (after PR merge).

### JOBS:
# deploy:
# 1. Generate build files.
# 2. Provide AWS credentials
# 3. Push build files to S3
# 4. Invalidate CloudFront distribution cache

name: 'Deploy Application'

on:
  push:
    branches:
      - main

    paths-ignore:
      - public
      - .gitignore
      - .prettierignore
      - .prettierrc.json
      - README.md

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build-static